chat/urls.py
from django.urls import path

from . import views
app_name = "chat"
urlpatterns = [
    path('<str:username>', views.room, name='room'),
    path('files/<str:username>', views.chatfiles, name='chatfiles'),
    path('video/', views.video, name="video"),
    path('hire/', views.hire, name="hire"),
    path('editbid/', views.edit_bid, name="editbid"),
    path('deliver/', views.deliver, name="deliver"),
    path('complete/', views.complete, name="complete"),
    path('join/', views.joincall, name="joincall")
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path("<str:username>", views.UserPostList.as_view(), name="posts"),
    path("", views.PostList.as_view(), name="allposts"),
    path('create/',
         views.MyPostCreate.as_view(success_url="/posts/"), name="createpost"),
    path('<int:pk>/', views.PostDetailView.as_view(),
         name="detailpost"),
    path('like/<int:pk>', views.like),
    path("liked/", views.LikedPostList.as_view(), name="likedposts"),
    path('unlike/<int:pk>', views.unlike),
    path('delete/<int:pk>',
         views.MyPostDeleteView.as_view(success_url="/posts/"),
         name="deleteposts"),
]

thinkgroupy/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings
from django.urls import path
from . import views
from . import contact
urlpatterns = [
    path('payments/', include('payments.urls', namespace="payments")),
    path('chat/', include('chat.urls', namespace="chat")),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include("accounts.urls", namespace="accounts")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('contact', contact.contact, name='contact'),
    path('terms', views.terms, name='terms'),
    path('partners', views.partners, name='partners'),
    path('privacy', views.privacy, name='privacy'),
    path('posts/', include("posts.urls", namespace="posts")),
    path('projects/', include("projects.urls", namespace="projects")),
    path('accounts/', include('allauth.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/pics/favicon.ico')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "thinkgroupy.views.handler404"
handler500 = "thinkgroupy.views.handler500"

posts/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth import get_user_model
from dashboard.models import Profile
User = get_user_model()


class MyPost(models.Model):
    pic = models.ImageField(
        upload_to="users/post_images/%y/%m/%d",
        null=True
    )
    subject = models.CharField(max_length=200)
    message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    uploaded_by = models.ForeignKey(to=Profile, on_delete=CASCADE, null=True)

    def __str__(self):
        return "%s" % self.subject


class PostComment(models.Model):
    post = models.ForeignKey(to=MyPost, on_delete=CASCADE)
    message = models.CharField(max_length=500)
    comented_by = models.ForeignKey(to=User, on_delete=CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    flag = models.CharField(max_length=20, null=True, blank=True,
                            choices=
                            (
                                ("racist", "racist"),
                                ("abusing", "abusing")
                            ))

    def __str__(self):
        return "%s" % self.message


class PostLike(models.Model):
    post = models.ForeignKey(to=MyPost, on_delete=CASCADE)
    Liked_by = models.ForeignKey(to=User, on_delete=CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.Liked_by

posts/forms.py
from django import forms
from .models import MyPost


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = MyPost
        fields = ['pic', 'subject', 'message']

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.views.generic.edit import CreateView, DeleteView
from braces.views import SelectRelatedMixin
from .models import MyPost, PostLike
from dashboard.models import FollowUser
from . import models
from django.contrib.auth import get_user_model
User = get_user_model()


class UserPostList(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    login_url = "accounts:signin"
    raise_exception = False

    model = models.MyPost
    select_related = ('uploaded_by',)
    context_object_name = 'myposts'
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        si = self.request.GET.get("si")
        if si is None:
            si = ""
        user = User.objects.get(username=self.kwargs['username'])
        postList = MyPost.objects.filter(Q(
            uploaded_by=user.profile)).filter(Q(subject__icontains=si)|Q(message__icontains=si)).order_by("-id");

        for p1 in postList:
            p1.liked = False
            ob = PostLike.objects.filter(post=p1, Liked_by=self.request.user.profile.user)
            if ob:
                p1.liked = True
        return postList


class MyPostCreate(LoginRequiredMixin, CreateView):
    login_url = "accounts:signin"
    raise_exception = False

    model = models.MyPost
    fields = ["pic", "subject", "message"]

    def form_valid(self, form):
        self.object = form.save()
        self.object.uploaded_by = self.request.user.profile
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    context_object_name = 'form'
    template_name = 'posts/mypost_form.html'


class LikedPostList(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    login_url = "accounts:signin"
    raise_exception = False

    model = models.PostLike
    select_related = ('Liked_by',)
    context_object_name = 'myposts'
    template_name = 'posts/liked_post_list.html'

    def get_context_data(self, **kwargs):
        context = generic.ListView.get_context_data(self, **kwargs)
        postList = PostLike.objects.filter(Liked_by=self.request.user.profile.user).order_by("-id");
        context["myposts"] = postList
        return context


class PostList(LoginRequiredMixin, TemplateView):
    login_url = "accounts:signin"
    raise_exception = False

    template_name = 'posts/post_list.html'

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        followedList = FollowUser.objects.filter(Followed_by=self.request.user)
        followedList2 = []
        for e in followedList:
            followedList2.append(e.profile)
        postList = MyPost.objects.filter(uploaded_by__in=followedList2).order_by("-id")

        for p1 in postList:
            p1.liked = False
            ob = PostLike.objects.filter(post=p1, Liked_by=self.request.user.profile.user)
            if ob:
                p1.liked = True
            obList = PostLike.objects.filter(post=p1)
            p1.likedno = obList.count()
        context["myposts"] = postList
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    login_url = "accounts:signin"
    raise_exception = False

    model = MyPost
    context_object_name = 'form'
    template_name = 'posts/post_detail.html'


class MyPostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = "accounts:signin"
    raise_exception = False

    model = MyPost
    context_object_name = 'form'
    template_name = 'posts/post_confirm_delete.html'


def like(req, pk):
    post = MyPost.objects.get(pk=pk)
    PostLike.objects.create(post=post, Liked_by=req.user.profile.user)
    return HttpResponseRedirect(redirect_to="/posts/")


def unlike(req, pk):
    post = MyPost.objects.get(pk=pk)
    PostLike.objects.filter(post=post, Liked_by=req.user.profile.user).delete()
    return HttpResponseRedirect(redirect_to="/posts/")

templates/posts/liked_post_list.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>Groupy posts</title>
{% endblock head %}

{% block body_block %}
<div id="layoutSidenav_content">
    <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
        <div class="container-fluid">
            <div class="page-header-content">
                <div class="row align-items-center justify-content-between pt-3">
                    <div class="col-auto mb-3">
                        <h1 class="page-header-title">
                            <div class="page-header-icon"><i data-feather="user"></i></div>
                            Liked Posts
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="sbp-preview-content">
            <div class="row">
                {% for likedpost in myposts %} 
                    <div  style="margin-top:1%" class="col-lg-4 col-md-12">
                        <div class="card">
                            <img class="card-img-top" style="width: 100%; height: 15vw; object-fit: cover;" src="{{likedpost.post.pic.url}}" alt="{{likedpost.post.subject}}">
                            <div class="card-body">
                                <h5 class="card-title">{{likedpost.post.subject}}</h5>
                                <a href="/posts/{{likedpost.post.id}}/">Read More</a>
                                <span style="float:right">
                                    <button class="btn btn-red btn-icon mr-2">
                                    <a class="btn btn-danger" href='/posts/unlike/{{likedpost.post.id}}'>
                                        <span class="fa fa-thumbs-down"></span>
                                    </a>
                                    </button>
                                    <button class="btn btn-yellow btn-icon mr-2">
                                        <i data-feather="bookmark"></i>
                                    </button>
                                    <button class="btn btn-blue btn-icon">
                                        <i data-feather="share"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </div>
</div>
{% endblock %}

templates/posts/mypost_form.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>{{user.username}} -Create Post</title>
        {% endblock head %}
{% block body_block %}

<div id="layoutSidenav_content">
    <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
        <div class="container-fluid">
            <div class="page-header-content">
                <div class="row align-items-center justify-content-between pt-3">
                    <div class="col-auto mb-3">
                        <h1 class="page-header-title">
                            <div class="page-header-icon"><i data-feather="user"></i></div>
                            Account -
                            <a href="{{user.profile.id}}"> {{user.username}}</a>
                            
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container mt-4">
        <nav class="nav nav-borders">
            <a class="nav-link active ml-0" href="#!">Create Post</a>
            <a class="nav-link" href="{% url 'posts:allposts' %}">All Posts</a>
        </nav>
        <hr class="mt-0 mb-4" />
        <div class="row">
            <div class="col-xl-12">
                <div class="card mb-4">
                    <div class="card-header">Create New Post</div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media}}
                            <div class="form-row">
                            <div class="form-group col-md-12">
                                <label class="small mb-1">Upload Pic</label>
                                {{form.pic}}
                            </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label class="small mb-1">Subject</label>
                                    <input class="form-control" type="text" name="subject" />
                                </div>
                                 <div class="form-group col-md-12">
                                     <label class="small mb-1">Message</label>
                                     {{ form.message|safe }}
                                </div>
                            </div>
                            <button class="btn btn-primary" type="submit">Create Post</button>
                </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/post_confirm_delete.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>{{user.username}}-Delete</title>
{% endblock head %}

{% block body_block %}
<div style="margin-top:1%" id="layoutSidenav_content">
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                <h5 class="alert-heading">Are you sure you want to delete this post?</h5>
            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
    </div>
    <div style="margin-top:1%">
<div class="container">
<div class="card card-header-actions mx-auto">
    <div class="card-header">
        Delete Post 
        <div>
            <form method="POST">
            {% csrf_token %}
                <button class="btn btn-red btn-icon mr-1">
                    <i data-feather="trash"><input value="Confirm Delete"></i>
                </button>
                <button class="btn btn-black btn-icon mr-2">
                    <a href="{% url 'posts:detailpost' pk=object.pk %}">
                    <i style="color:white" data-feather="arrow-left-circle"></i>
                </a>
            </button>
            </form>
        </div>
    </div>
    <div class="card-body">
        <div class="sbp-preview-content">
            <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <img class="card-img-top" src="{{form.pic.url}}" alt="{{post.subject}}">
                            <div class="card-body">
                                <h5 class="card-title">{{form.subject}}</h5>
                                <p class="card-title">{{form.message}}</p>
                                <a href="/profile/{{form.uploaded_by.id}}">{{form.uploaded_by}}</a>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>{{user.username}} - posts</title>
{% endblock head %}

{% block body_block %}
<div id="layoutSidenav_content">
<div style="margin-top:1%">
<div class="container">
<div class="card card-header-actions mx-auto">
    <div class="card-header">
        Post Detail
        <div>
            <button class="btn btn-red btn-icon mr-2">
                <a style="color:black;" href="{% url 'posts:deleteposts' pk=object.pk %}">
                <i data-feather="trash"></i>
                </a>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="sbp-preview-content">
            <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <img class="card-img-top" src="{{form.pic.url}}" alt="{{post.subject}}">
                            <div class="card-body">
                                <h5 class="card-title">{{form.subject}}</h5>
                                <p class="card-title">{{form.message}}</p>
                                <a href="/profile/{{form.uploaded_by.id}}">{{form.uploaded_by}}</a>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/posts/post_list.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>Groupy posts</title>
{% endblock head %}

{% block body_block %}
<div id="layoutSidenav_content">
    <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
        <div class="container-fluid">
            <div class="page-header-content">
                <div class="row align-items-center justify-content-between pt-3">
                    <div class="col-auto mb-3">
                        <h1 class="page-header-title">
                            <div class="page-header-icon"><i data-feather="user"></i></div>
                            All Posts
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="sbp-preview-content">
            <div class="row">
                {% for post in myposts %} 
                    <div  style="margin-top:1%" class="col-lg-4 col-md-12">
                        <div class="card">
                            <img class="card-img-top" style="width: 100%; height: 15vw; object-fit: cover;" src="{{post.pic.url}}" alt="{{post.subject}}">
                            <div class="card-body">
                                <h5 class="card-title">{{post.subject}}<p style="float:right">{{post.uploaded_by}}</p></h5>
                                <a href="/posts/{{post.id}}/">Read More</a>
                                <span style="float:right">
                                    {% if post.liked %}
                                    <button class="btn btn-red btn-icon mr-2">
                                    <a class="btn btn-danger" href='/posts/unlike/{{post.id}}'>
                                        <span class="fa fa-thumbs-down"></span>
                                    </a>
                                    </button>
                                    {% else %}
                                    <button class="btn btn-teal btn-icon mr-2">
                                    <a class="btn btn-success" href='/posts/like/{{post.id}}'>
                                        <span class="fa fa-thumbs-up"></span>
                                    </a>
                                    </button>
                                    {% endif %}
                                    <button class="btn btn-yellow btn-icon mr-2">
                                        <i data-feather="bookmark"></i>
                                    </button>
                                    <button class="btn btn-blue btn-icon">
                                        <i data-feather="share"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </div>
</div>
{% endblock %}

templates/posts/user_post_list.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>{{user.username}} - posts</title>
{% endblock head %}

{% block body_block %}
<div id="layoutSidenav_content">
    <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
        <div class="container-fluid">
            <div class="page-header-content">
                <div class="row align-items-center justify-content-between pt-3">
                    <div class="col-auto mb-3">
                        <h1 class="page-header-title">
                            <div class="page-header-icon"><i data-feather="user"></i></div>
                            Posts-<a href="/profile/{{user.profile.id}}">{{user.username}}</a>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="sbp-preview-content">
            <div class="row">
                {% for post in myposts %} 
                    <div  style="margin-top:1%" class="col-lg-4 col-md-12">
                        <div class="card">
                            <img class="card-img-top" style="width: 100%; height: 15vw; object-fit: cover;" src="{{post.pic.url}}" alt="{{post.subject}}">
                            <div class="card-body">
                                <h5 class="card-title">{{post.subject}}</h5>
                                <a href="{% url 'posts:detailpost' pk=post.id %}">Read More</a>
                                <span style="float:right">
                                    {% if post.liked %}
                                    <button class="btn btn-red btn-icon mr-2">
                                    <a class="btn btn-danger" href='/posts/unlike/{{post.id}}'>
                                        <span class="fa fa-thumbs-down"></span>
                                    </a>
                                    </button>
                                    {% else %}
                                    <button class="btn btn-teal btn-icon mr-2">
                                    <a class="btn btn-success" href='/posts/like/{{post.id}}'>
                                        <span class="fa fa-thumbs-up"></span>
                                    </a>
                                    </button>
                                    {% endif %}
                                    <button class="btn btn-teal btn-icon mr-2">
                                        <i data-feather="bookmark"></i>
                                    </button>
                                    <button class="btn btn-blue btn-icon">
                                        <i data-feather="share"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </div>
</div>
{% endblock %}