accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('signup', views.signup, name="signup"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('signin', views.signin, name="signin"),
    path('signout', views.signout, name="signout"),
    path('confirm_your_account', views.confirm_your_account, name="confirm_your_account"),
    path('account_activated', views.account_activated, name="account_activated"),
    path('account_activated_false', views.account_activated_false, name="account_activated_false"),
 
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

chat/urls.py
from django.urls import path

from . import views
app_name = "chat"
urlpatterns = [
    path('<str:username>', views.room, name='room'),
    path('files/<str:username>', views.chatfiles, name='chatfiles'),
    path('video/', views.video, name="video"),
    path('hire/', views.hire, name="hire"),
    path('editbid/', views.edit_bid, name="editbid"),
    path('deliver/', views.deliver, name="deliver"),
    path('complete/', views.complete, name="complete"),
    path('join/', views.joincall, name="joincall")
]

thinkgroupy/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings
from django.urls import path
from . import views
from . import contact
urlpatterns = [
    path('payments/', include('payments.urls', namespace="payments")),
    path('chat/', include('chat.urls', namespace="chat")),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include("accounts.urls", namespace="accounts")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('contact', contact.contact, name='contact'),
    path('terms', views.terms, name='terms'),
    path('partners', views.partners, name='partners'),
    path('privacy', views.privacy, name='privacy'),
    path('posts/', include("posts.urls", namespace="posts")),
    path('projects/', include("projects.urls", namespace="projects")),
    path('accounts/', include('allauth.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/pics/favicon.ico')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "thinkgroupy.views.handler404"
handler500 = "thinkgroupy.views.handler500"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import SignUpForm
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags
from thinkgroupy import settings
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
import requests
UserModel = get_user_model()


def confirm_your_account(request):
    return render(request, 'accounts/confirm_account.html')


def account_activated(request):
    return render(request, 'accounts/account_activated.html')


def account_activated_false(request):
    return render(request, 'accounts/account_activated_false.html')


def signup(request):
    if request.user.is_authenticated:
        return redirect('dashboard:dashboard')
    else:
        form = SignUpForm()
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False,)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                to_email = form.cleaned_data.get('email')
                post_data = {'fields[email]': to_email, 'fields[name]': request.POST.get('first_name'), 'fields[last_name]': request.POST.get('last_name'), 'ml-submit': '1', 'anticsrf': True}
                requests.post('https://static.mailerlite.com/webforms/submit/k7y7q6', data=post_data)
                html_content = render_to_string('accounts/activation_mail.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': default_token_generator.make_token(user),
                })
                text_content = strip_tags(html_content)
                email = EmailMultiAlternatives(mail_subject, text_content, settings.EMAIL_HOST_USER, [to_email])
                email.attach_alternative(html_content, "text/html")
                email.send()
                return redirect('accounts:confirm_your_account')
            else:
                form = SignUpForm()
                messages = " "
                return render(request, 'accounts/signup.html', {'form': form, 'messages': messages})
        else:
            form = SignUpForm()
            return render(request, 'accounts/signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        to_email = user.email
        html_content = render_to_string('accounts/welcome_email.html')
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives('Welcome To Thinkgroupy', text_content, settings.EMAIL_HOST_USER, [to_email])
        email.attach_alternative(html_content, "text/html")
        email.send()
        return redirect('accounts:account_activated')
    else:
        return redirect('accounts:account_activated_false')


def signin(request):
    if request.GET:
        next_page = request.GET['next']
        if request.user.is_authenticated:
            return HttpResponseRedirect(next_page)
    if request.user.is_authenticated:
        return redirect('dashboard:dashboard')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            rememberme = request.POST.get('rememberme')
            if rememberme is not None:
                request.session.set_expiry(604800)
            else:
                request.session.set_expiry(0)
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                if 'next_page' in locals():
                    return HttpResponseRedirect(next_page)
                else:
                    return redirect('dashboard:dashboard')
            else:
                messages.info(request, 'Username OR password is incorrect')
        context = {}
        return render(request, 'accounts/signin.html', context)


def signout(request):
    logout(request)
    return redirect('accounts:signin')

templates/accounts/account_activated.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy</title>
{% endblock head %}

{% block body_block%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body text-center"><div class="h1 font-weight-light mb-0"><h1>Confirm Your Account</h1></div></div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                            <p>Thank you for your email confirmation. Now you can <a href="signin">login</a> your account.</p>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body px-5 py-4">
                        <div class="small text-center">
                            Already have an account?
                            <a href="/signin">Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/accounts/account_activated_false.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy</title>
{% endblock head %}

{% block body_block%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body text-center"><div class="h1 font-weight-light mb-0"><h1>Confirm Your Account</h1></div></div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                            <p>The email confirmation link was invalid, possibly because it has already been used.
Please request a new <a href="{% url 'accounts:password_reset' %}">password reset</a>or make account with new email id.</p>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body px-5 py-4">
                        <div class="small text-center">
                            New user?
                            <a href="/signup">Create an account!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/accounts/confirm_account.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy</title>
{% endblock head %}

{% block body_block%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body text-center"><div class="h1 font-weight-light mb-0"><h1>Confirm Your Account</h1></div></div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                        <p>We’ve emailed you instructions for setting your Account. If the email you entered exist. You should receive it shortly.</p>
                        <p>If you don’t receive an email, please make sure you’ve entered the correct address, and check your <strong>spam or Promotions folder.</strong></p>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body px-5 py-4">
                        <div class="small text-center">
                            New user?
                            <a href="/signup">Create an account!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/accounts/login_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177632222-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-177632222-1');
</script>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block head %}
        <title>Thinkgroupy | re-imagine your boundaries</title>
        {% endblock head %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/header.css'%}">
        <link rel="icon" type="image/x-icon" href="{% static 'pics/thinkgroupy.jpg' %}" />
        <script data-search-pseudo-elements defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.27.0/feather.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/app.js' %}"></script>
    </head>
    <body>
        <nav class="menubar">
        <h1 class="logotext"><a href="/">Thinkgroupy</a></h1>
        <ul class="menuitems">
            <a href="/"><li>Home</li></a>
            {% if user.is_authenticated %}
                <a href="/dashboard"><li>Dashboard</li></a>
                <a href="/signout"><li>Logout</li></a>
            {% else %}         
            <a href="/signup"><li>Signup</li></a>
            <a href="/signin"><li>Login</li></a>
            {% endif %}
            <a href="/partners"><li>Partners</li></a>
            <a href="/contact"><li>Contact</li></a>
        </ul>
        <img src="{% static 'pics/Hamburger_icon.svg.png' %}" alt="" class="hamburger" onclick="clicked()">
    </nav> 
    <ul class="menuitems2">
        <a href="/"><li>Home</li></a>
        {% if user.is_authenticated %}
            <a href="/dashboard"><li>Dashboard</li></a>
            <a href="/signout"><li>Logout</li></a>
        {% else %}         
        <a href="/signup"><li>Signup</li></a>
        <a href="/signin"><li>Login</li></a>
        {% endif %}
        <a href="/partners"><li>Partners</li></a>
        <a href="/contact"><li>Contact</li></a>
    </ul>
        <div class="bg-primary" style="margin-top: 80px;">
            <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                {% block body_block %}
      
                 {% endblock %}
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="footer mt-auto footer-dark">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6 small">Copyright &copy; Thinkgroupy 2020</div>
                            <div class="col-md-6 text-md-right small">
                                <a href="/privacy">Privacy Policy</a>
                                &middot;
                                <a href="/terms">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        </div>
        <script>
  function initFreshChat() {
    window.fcWidget.init({
      token: "e1bedc69-4845-4f44-b0df-5df34cf6b735",
      host: "https://wchat.in.freshchat.com"
    });
  }
  function initialize(i,t){var e;i.getElementById(t)?initFreshChat():((e=i.createElement("script")).id=t,e.async=!0,e.src="https://wchat.in.freshchat.com/js/widget.js",e.onload=initFreshChat,i.head.appendChild(e))}function initiateCall(){initialize(document,"freshchat-js-sdk")}window.addEventListener?window.addEventListener("load",initiateCall,!1):window.attachEvent("load",initiateCall,!1);
</script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/accounts/signin.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy - signin</title>
{% endblock head %}

{% block body_block%}
{% load socialaccount %}
{% providers_media_js %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body p-5 text-center">
                        <div class="h3 font-weight-light mb-3">Sign In</div>
                        {% if messages %}
                            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                            {% for message in messages %}
                            <h5 class="alert-heading">{{ message }}</h5>
                            {% endfor %}
                            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                            </div>
                        {% endif %}
                        <a class="btn btn-icon btn-facebook mx-1" href="{% url 'facebook_login' %}"><i class="fab fa-facebook-f fa-fw fa-sm"></i></a>
                        <a class="btn btn-icon btn-github mx-1" href="{% url 'github_login' %}"><i class="fab fa-github fa-fw fa-sm"></i></a>
                        <a class="btn btn-icon" href="{% url 'google_login' %}"><img width="100%" height="100%" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"></a>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                        <form method="POST" action="">
                        {% csrf_token %}
                            <div class="form-group">
                                <label class="text-gray-600 small" for="emailExample">Username</label>
                                <input type="text" class="form-control form-control-solid py-4" name="username" required="required">
                            </div>
                            <div class="form-group">
                                <label class="text-gray-600 small" for="passwordExample">Password</label>
                                <input type="password" class="form-control form-control-solid py-4" name="password" required="required">
                            </div>
                            <div class="form-group"><a class="small" href="{% url 'accounts:password_reset' %}">Forgot your password?</a></div>
                            <div>
                                <div class="custom-control custom-control-solid custom-checkbox">
                                    <input class="custom-control-input small" id="customCheck1" type="checkbox" name="rememberme" />
                                    <label class="custom-control-label" for="customCheck1">Remember password</label>
                                </div>
                                <button type="submit" class="btn btn-primary" name="signin">Login</button>
                            </div>
                        </form>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body px-5 py-4">
                        <div class="small text-center">
                            New user?
                            <a href="signup">Create an account!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/accounts/signup.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}

{% load static %}
{% block head %}
        <title>Thinkgroupy - signup</title>
{% endblock head %}

{% block body_block %}
{% load socialaccount %}
{% providers_media_js %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-9">
                <div class="card my-5">
                    <div class="card-body p-5 text-center">
                        <div class="h3 font-weight-light mb-3">Create an Account</div>
                        <div class="small text-muted mb-2">Sign up using...</div>
                        <a class="btn btn-icon btn-facebook mx-1" href="{% url 'facebook_login' %}"><i class="fab fa-facebook-f fa-fw fa-sm"></i></a>
                        <a class="btn btn-icon btn-github mx-1" href="{% url 'github_login' %}"><i class="fab fa-github fa-fw fa-sm"></i></a>
                        <a class="btn btn-icon" href="{% url 'google_login' %}"><img width="100%" height="100%" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"></a>
                    </div>
                    <hr class="my-0" />
                    {% if messages %}
                        <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        <h5 class="alert-header">Error! one of these could be the reason.</h5>
                        <li class="alert-body">☻ Your password must conatins atleast 8 characters.</li>
                        <li class="alert-body">☻ Make sure your password matches with confirm password.</li>
                        <li class="alert-body">☻ Your password must be a <strong>strong password (ex: Think@groupy#19).</strong></li>
                        <li class="alert-body">☻ Username already exist.</li>
                        <li class="alert-body">☻ Email already exist.</li>
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                        </div>
                    {% endif %}
                    <div class="card-body p-5">
                        <div class="text-center small text-muted mb-4">...or enter your information below.</div>
                        <form method="POST" action="">
                        {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="text-gray-600 small">First name</label>
                                         <input class="form-control form-control-solid py-4" type="text" name="first_name" required/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="text-gray-600 small">Last name</label>
                                        <input class="form-control form-control-solid py-4" type="text" name="last_name" required/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="text-gray-600 small">Username</label>
                                        <input class="form-control form-control-solid py-4" type="text" name="username" required/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="text-gray-600 small">Email address</label>
                                        <input class="form-control form-control-solid py-4" type="email" name="email" required/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="text-gray-600 small">Password</label>
                                        <input class="form-control form-control-solid py-4" type="password" name="password1" required/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="text-gray-600 small">Confirm Password</label>
                                        <input class="form-control form-control-solid py-4" type="password" name="password2" required/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between">
                                <div class="custom-control custom-control-solid custom-checkbox">
                                    <input class="custom-control-input small" id="customCheck1" type="checkbox" required/>
                                    <label class="custom-control-label mr-3" for="customCheck1">
                                        I accept the
                                        <a href="/terms">terms &amp; conditions</a>
                                        .
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary" name="reg_user">Create Account</button>
                            </div>
                        </form>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body px-5 py-4">
                        <div class="small text-center">
                            Have an account?
                            <a href="signin">Sign in!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}