chat/urls.py
from django.urls import path

from . import views
app_name = "chat"
urlpatterns = [
    path('<str:username>', views.room, name='room'),
    path('files/<str:username>', views.chatfiles, name='chatfiles'),
    path('video/', views.video, name="video"),
    path('hire/', views.hire, name="hire"),
    path('editbid/', views.edit_bid, name="editbid"),
    path('deliver/', views.deliver, name="deliver"),
    path('complete/', views.complete, name="complete"),
    path('join/', views.joincall, name="joincall")
]

dashboard/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "dashboard"
urlpatterns = [
    path('otp/<str:email2>', views.otp_verify, name="otp_verify"),
    path('dashboard', views.dashboard, name="dashboard"),
    path("users", views.UserListView.as_view(), name="users"),
    path('profile/follow/<int:pk>', views.follow, name="follow"),
    path('profile/unfollow/<int:pk>', views.unfollow, name="unfollow"),
    path('profile/<pk>', views.ProfileDetailView, name="profile"),
    path('editprofilepic', views.EditProfilePic, name="editprofilepic"),
    path('editprofile', views.EditProfile, name="editprofile"),
    path('change_password', views.change_password, name='change_password'),
    path('security', views.security, name="security"),
    path('EmailUpdate', views.EmailUpdate, name="EmailUpdate"),
    path('email_activated', views.email_activated, name="email_activated"),
    path('email_activated_false', views.email_activated_false, name="email_activated_false"),
    path('PhoneUpdate', views.PhoneUpdate, name="PhoneUpdate"),
    path('otp_phone_veify/<str:phone>', views.otp_phone_verify, name="otp_phone_verify"),
    path('delete/profile/<int:pk>', views.DeleteUser.as_view(), name="delete"),
    path('notify/', views.notify, name="notify"),
    path('billing', views.billing, name="billing"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = "projects"
urlpatterns = [
    path("", views.Projects, name="projects"),
    path("my", views.Myprojects, name="my_project"),
    path("new/", views.CreateProject, name="create"),
    path("category", views.category, name="category"),
    path("buy_emails", views.buy_emails, name="buy_emails"),
    path("<str:category>", views.Category_Project, name="category_project"),
    path("project/<str:slug>", views.Slug_Project, name="slug_project"),
    path("apply/<slug:project>", views.BidProject, name="bid_project"),
    path("bids/<slug:project>", views.Applicants, name="applicants"),
    path("orders/", views.orders, name="orders")
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thinkgroupy/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings
from django.urls import path
from . import views
from . import contact
urlpatterns = [
    path('payments/', include('payments.urls', namespace="payments")),
    path('chat/', include('chat.urls', namespace="chat")),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include("accounts.urls", namespace="accounts")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('contact', contact.contact, name='contact'),
    path('terms', views.terms, name='terms'),
    path('partners', views.partners, name='partners'),
    path('privacy', views.privacy, name='privacy'),
    path('posts/', include("posts.urls", namespace="posts")),
    path('projects/', include("projects.urls", namespace="projects")),
    path('accounts/', include('allauth.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/pics/favicon.ico')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "thinkgroupy.views.handler404"
handler500 = "thinkgroupy.views.handler500"

dashboard/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True,
                                on_delete=models.CASCADE)
    gender = models.CharField(max_length=200, null=True, blank=True)
    organization_name = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    birth_day = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to="users/profile/%y/%m/%d",
                              default="users/person_1.png")
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

#     def save(self, *args, **kwargs):
#         super(Profile, self).save(*args, **kwargs)

#         img = Image.open(self.image.path)

#         if img.height > 200 or img.width > 200:
#             output_size = (200, 200)
#             img.thumbnail(output_size)
#             img.save(self.image.path)

    def get_absolute_url(self):
        return reverse("dashboard:profile", kwargs={'pk': self.pk})


class PrimaryEmail(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    email = models.EmailField(max_length=240, default="example@email.com")
    token = models.CharField(max_length=12, null=True)
    verified = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    errors = models.IntegerField(default=0)


@receiver(models.signals.post_save, sender=User)
def post_save_user_signal(sender, instance, created, **kwargs):
    if created:
        instance.save()


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)


class UserPhone(models.Model):
    phone = models.CharField(max_length=15,
                             unique=True,
                             null=True, blank=True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    token = models.CharField(max_length=12, null=True)
    verified = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    errors = models.IntegerField(default=0)


class FollowUser(models.Model):
    profile = models.ForeignKey(to=Profile, on_delete=models.CASCADE)
    Followed_by = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % self.Followed_by

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, UserPhone


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']


class EmailUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email']


class PhoneUpdateForm(forms.ModelForm):

    class Meta:
        model = UserPhone
        fields = ['phone']


class OtpForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email']

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.db.models import Q
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from thinkgroupy import settings
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import ProfileUpdateForm, PhoneUpdateForm
from django.contrib.auth import get_user_model
from .models import Profile
from .models import FollowUser, PrimaryEmail, UserPhone
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils import timezone
from datetime import timedelta
import secrets
from twilio.rest import Client
from chat.models import Notify
from django.views.decorators.csrf import csrf_exempt
import json
from payments.models import VirtualCurrency, AccountDetails, Tempwallet, Refund
from projects.models import CompletedOrder, Order
import base64
import matplotlib
import matplotlib.pyplot as xyz
from io import BytesIO
from decouple import config
matplotlib.use('Agg')
UserModel = get_user_model()


@csrf_exempt
def notify(request):
    if request.method == "POST":
        notifications = int(request.POST.get('unread'))
        if notifications <= 0:
            return HttpResponse(json.dumps({"hello": "1"}), content_type="application/json")
        else:
            x = Notify.objects.filter(user=User.objects.get(username=request.POST.get('user')))
            for i in x:
                i.read = True
                i.save()
            return HttpResponse(json.dumps({"hello": "1"}), content_type="application/json")


@login_required
def dashboard(request):
    user = request.user
    if VirtualCurrency.objects.filter(user=request.user).exists():
        pass
    else:
        obj = VirtualCurrency(user=user)
        obj.save()
    if Refund.objects.filter(user=request.user).exists():
        pass
    else:
        obje = Refund(user=user)
        obje.save()
    time = []
    monthly = 0
    yearly = 0
    Jan = 0
    Feb = 0
    Mar = 0
    Apr = 0
    May = 0
    Jun = 0
    Jul = 0
    Aug = 0
    Sep = 0
    Oct = 0
    Nov = 0
    Dec = 0
    if CompletedOrder.objects.filter(user=request.user).exists():
        com = CompletedOrder.objects.filter(user=request.user).count()
        x = CompletedOrder.objects.filter(user=request.user)
        for i in x:
            print(timezone.now().month == i.completed_on.month)
            if timezone.now().month == i.completed_on.month:
                monthly += i.budget
            if timezone.now().year == i.completed_on.year:
                yearly += i.budget
            if i.completed_on.month == 1:
                Jan += i.budget
            elif i.completed_on.month == 2:
                Feb += i.budget
            elif i.completed_on.month == 3:
                Mar += i.budget
            elif i.completed_on.month == 4:
                Apr += i.budget
            elif i.completed_on.month == 5:
                May += i.budget
            elif i.completed_on.month == 6:
                Jun += i.budget
            elif i.completed_on.month == 7:
                Jul += i.budget
            elif i.completed_on.month == 8:
                Aug += i.budget
            elif i.completed_on.month == 9:
                Sep += i.budget
            elif i.completed_on.month == 10:
                Oct += i.budget
            elif i.completed_on.month == 11:
                Nov += i.budget
            elif i.completed_on.month == 12:
                Dec += i.budget
        graph = [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
        months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        labels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] 
        img = BytesIO()

        xyz.plot(months, graph)
        xyz.xticks(months, labels)
        xyz.ylabel('Earning(Rs.)')
        xyz.xlabel('Months')
        xyz.savefig(img, format='png')
        xyz.close()
        img.seek(0)
        plot_url = base64.b64encode(img.getvalue()).decode('utf8')
    else:
        com = 0
    if Order.objects.filter(worker=request.user).exists():
        progress = Order.objects.filter(worker=request.user)
        for prog in progress:
            time.append((prog.bid.project.name, 100/(prog.bid.date_time- prog.created_on).days))
    elif Order.objects.filter(creator=request.user).exists():
        progress = Order.objects.filter(creator=request.user)
        for prog in progress:
            time.append((prog.bid.project.name, 100/(prog.bid.date_time- prog.created_on).days))
    else:
        progress = "no"
        time = "no"
    if "plot_url" not in locals():
        plot_url = "no"
    return render(request, 'dashboard/dashboard.html', {"time": time, "com": com, "monthly": monthly, "yearly": yearly, "plot": plot_url})


def ProfileDetailView(request, pk):
    form = Profile.objects.get(pk=pk)
    user = FollowUser.objects.filter(profile=form, Followed_by=request.user)

    if user:
        is_followed = True
    else:
        is_followed = False
    return render(request, 'dashboard/profile_detail.html', {'form': form, 'is_followed': is_followed})


def follow(req, pk):
    user = Profile.objects.get(pk=pk)
    FollowUser.objects.create(profile=user, Followed_by=req.user.profile.user)
    return redirect('dashboard:profile', pk)


def unfollow(req, pk):
    user = Profile.objects.get(pk=pk)
    FollowUser.objects.filter(profile=user, Followed_by=req.user.profile.user).delete()
    return redirect('dashboard:profile', pk)


class UserListView(LoginRequiredMixin, ListView):
    login_url = "accounts:signin"
    raise_exception = False

    model = Profile
    context_object_name = 'users'
    template_name = 'dashboard/user_list.html'

    def get_queryset(self):
        si = self.request.GET.get("si")
        if si:
            user = User.objects.get(username=si)
            profList = Profile.objects.filter(Q(user=user)|Q(location__icontains = si)|Q(gender__icontains = si)|Q(organization_name__icontains = si)).order_by("-id");
        else:
            si=""
            profList = Profile.objects.filter(Q(location__icontains = si)|Q(gender__icontains = si)|Q(organization_name__icontains = si)).order_by("-id");
        for p1 in profList:
            p1.followed = False
            ob = FollowUser.objects.filter(profile=p1, Followed_by=self.request.user)
            if ob:
                p1.followed = True
        return profList


@login_required
def EditProfile(request):
    context = {}
    data = Profile.objects.get(user__id=request.user.id)
    context["data"] = data
    if request.method == "POST":
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        gender = request.POST["gender"]
        organization_name = request.POST["organization"]
        location = request.POST["location"]
        birth_day = request.POST["birth_day"]

        user = User.objects.get(id=request.user.id)
        user.first_name = first_name
        user.last_name = last_name
        user.save()

        data.gender = gender
        data.organization_name = organization_name
        data.location = location
        data.birth_day = birth_day
        data.completed = True
        data.save()
        context["status"] = "Changes saved successfully"
    return render(request, 'dashboard/editprofile.html', context)


@login_required
def EditProfilePic(request):
    if request.method == "POST":
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, 'Your Picture was successfully updated!')
            return render(request, 'dashboard/editprofile.html')
        else:
            messages.error(request, 'Try again!')
    else:
        return render(request, 'dashboard/editprofile.html')


@login_required
def security(request):
    return render(request, 'dashboard/security.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request,
                             'Your password was successfully updated!')
            return render(request, 'dashboard/security.html')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'dashboard/security.html', {
        'form': form
    })


class DeleteUser(LoginRequiredMixin, generic.DeleteView):
    login_url = "/signin/"
    model = User
    template_name = 'dashboard/security.html'
    success_url = reverse_lazy("index")


def email_activated(request):
    return render(request, 'dashboard/email_activated.html')


def email_activated_false(request):
    return render(request, 'dashboard/email_activated_false.html')


@login_required(login_url='signin')
def EmailUpdate(request):
    user = request.user
    if request.method == 'POST':
        email_for_activation = request.POST['email']
        token = secrets.randbits(16)
        mail_subject = 'Confirm your Mail'
        html_content = render_to_string("dashboard/confirm_mail.html",
                                        {'otp': token})
        text_content = strip_tags(html_content)

templates/dashboard/email_activated.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy</title>
{% endblock head %}

{% block body_block%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body text-center"><div class="h1 font-weight-light mb-0"><h1>Confirm Your Email</h1></div></div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                            <p>Thank you for your email confirmation. Your email has been changed successfully.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/dashboard/email_activated_false.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy</title>
{% endblock head %}

{% block body_block%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body text-center"><div class="h1 font-weight-light mb-0"><h1>Confirm Your Email</h1></div></div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                        <p>The email confirmation link was invalid, possibly because it has already been used. Please try again.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/dashboard/otp.html
<!DOCTYPE html>
{% extends 'accounts/login_base.html' %}
{% load static %}

{% block head %}
        <title>Thinkgroupy</title>
{% endblock head %}

{% block body_block%}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 col-sm-11">
                <div class="card my-5">
                    <div class="card-body p-5 text-center">
                        <div class="h3 font-weight-light mb-3">ONE TIME PASSWORD</div>
                        {% if messages %}
                            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                            {% for message in messages %}
                            <h5 class="alert-heading">{{ message }}</h5>
                            {% endfor %}
                            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                            </div>
                        {% endif %}
                        {% if errors %}
                            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                            <h5 class="alert-heading">O.T.P was wrong.</h5>
                            <p>attempts left - {{errors}}</p>
                            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                            </div>
                        {% endif %}
                    </div>
                    <hr class="my-0" />
                    <div class="card-body p-5">
                        <form method="POST" action="otp_verify">
                        {% csrf_token %}
                            <div class="form-group">
                                <label class="text-gray-600 small">O.T.P</label>
                                <input type="text" class="form-control form-control-solid py-4" name="otp" required="required" placeholder="Enter your O.T.P">
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary">Verify</button>
                            </div>
                        </form>
                    </div>
                    <hr class="my-0" />
                    <div class="card-body px-5 py-4">
                        <div class="small text-center">
                            Didn't recieved?
                            <a href="/security">Request new!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/dashboard/security.html
<!DOCTYPE html>
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block head %}
        <title>{{user.username}} - profile</title>
        {% endblock head %}
{% block body_block %}
 
<div id="layoutSidenav_content">
                <main>
                    <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                        <div class="container-fluid">
                            <div class="page-header-content">
                                <div class="row align-items-center justify-content-between pt-3">
                                    <div class="col-auto mb-3">
                                        <h1 class="page-header-title">
                                            <div class="page-header-icon"><i data-feather="user"></i></div>
                                            Account Security -<a href="editprofile">{{user.username}}</a>
                                        </h1>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if messages %}
                            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                            {% for message in messages %}
                            <h5 class="alert-heading">{{ message }}</h5>
                            {% endfor %}
                            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span></button>
                            </div>
                        {% endif %}
                    </header>
                    <div class="container mt-4">
                        <nav class="nav nav-borders">
                            <a class="nav-link ml-0" href="/editprofile">Profile</a>
                            <a class="nav-link" href="/billing">billing</a>
                            <a class="nav-link active" href="/security">Security</a>
                        </nav>
                        <hr class="mt-0 mb-4" />
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="card mb-4">
                                    <div class="card-header">Change Password</div>
                                    <div class="card-body">
                                        <form method="POST" action="change_password">
                                        {% csrf_token %}
                                            <div class="form-group">
                                                <label class="small mb-1" for="currentPassword">Current Password</label>
                                                <input class="form-control" id="currentPassword" type="password" placeholder="Enter current password" name="old_password" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="newPassword">New Password</label>
                                                <input class="form-control" id="newPassword" type="password" placeholder="Enter new password" name="new_password1" />
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="confirmPassword">Confirm Password</label>
                                                <input class="form-control" id="confirmPassword" type="password" placeholder="Confirm new password" name="new_password2"/>
                                            </div>
                                            <button class="btn btn-primary" type="submit">Save</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="card mb-4">
                                    <div class="card-header">Security Preferences</div>
                                    <div class="card-body">
                                        <h5 class="mb-1">Account Privacy</h5>
                                        <p class="small text-muted">By setting your account to private, your profile information and posts will not be visible to users outside of your user groups.</p>
                                        <form>
                                            <div class="custom-control custom-radio">
                                                <input class="custom-control-input" id="radioPublic" type="radio" name="radioPrivacy" checked />
                                                <label class="custom-control-label" for="radioPublic">Public (posts are available to all users)</label>
                                            </div>
                                            <div class="custom-control custom-radio">
                                                <input class="custom-control-input" id="radioPrivate" type="radio" name="radioPrivacy" />
                                                <label class="custom-control-label" for="radioPrivate">Private (posts are available to only users in your groups)</label>
                                            </div>
                                        </form>
                                        <hr class="my-4" />
                                        <h5 class="mb-1">Data Sharing</h5>
                                        <p class="small text-muted">Sharing usage data can help us to improve our products and better serve our users as they navigation through our application. When you agree to share usage data with us, crash reports and usage analytics will be automatically sent to our development team for investigation.</p>
                                        <form>
                                            <div class="custom-control custom-radio">
                                                <input class="custom-control-input" id="radioUsageYes" type="radio" name="radioUsage" checked />
                                                <label class="custom-control-label" for="radioUsageYes">Yes, share data and crash reports with app developers</label>
                                            </div>
                                            <div class="custom-control custom-radio">
                                                <input class="custom-control-input" id="radioUsageNo" type="radio" name="radioUsage" />
                                                <label class="custom-control-label" for="radioUsageNo">No, limit my data sharing with app developers</label>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card mb-4">
                                    <div class="card-header">Change Email</div>
                                    <div class="card-body">
                                        <form method="POST" action="{% url 'dashboard:EmailUpdate' %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                                <label class="small mb-1" >Email</label>
                                                <input class="form-control" type="email" placeholder="Enter New Email" required name="email"/>
                                            </div>
                                        <button class="btn btn-primary" type="submit">save</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="card mb-4">
                                    <div class="card-header">Number (Include Country code) </div>
                                    <div class="card-body">
                                        <form method="POST" action="{% url 'dashboard:PhoneUpdate' %}">
                                        {% csrf_token %}
                                        <div class="form-group">
                                                <label class="small mb-1">Number</label>
                                                <input class="form-control" type="tel" placeholder="+91 9988776655" required name="phone"/>
                                            </div>
                                        <button class="btn btn-primary" type="submit">save</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="card mb-4">
                                    <div class="card-header">Delete Account</div>
                                    <div class="card-body">
                                        <p>Deleting your account is a permanent action and cannot be undone. If you are sure you want to delete your account, select the button below.</p>
                                        <form method="POST" action="delete/profile/{{user.id}}">
                                        {% csrf_token %}
                                        <button class="btn btn-danger-soft text-danger" type="submit">I understand, delete my account</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
{% endblock %}